name: Deploy PR to test environment
on:
  pull_request:
    types: labeled

jobs:
  build:
    name: Build docker image
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/valimail/kube_pipeline_test:${{ github.sha }}
  deploy-stage:
    name: Deploy to stage
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    needs: build
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VALIMAIL_APP_STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VALIMAIL_APP_STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Add version suffix
        uses: ./.github/actions/add-version-suffix
        with:
          env: stage
          version: pr${{ github.event.number }}
      - name: Deploy to kubernetes
        uses: ./.github/actions/deploy
        with:
          env: stage
          cluster: valimail-app-staging
