name: Deploy to production
on:
  push:
    tags:
      - deploy/prod/*
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VALIMAIL_APP_PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VALIMAIL_APP_PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy to kubernetes
        uses: ./.github/actions/deploy
        with:
          env: prod
          cluster: valimail-app-prod
